openapi: 3.0.1
info:
    title: BCNC API
    description: API documentation for BCNC Hexagonal Prueba
    version: "1.0"
servers:
    - url: http://localhost:8080
      description: Generated server url
tags:
    - name: Price
      description: Price API for price related calls
    - name: Echo
      description: API testeo CICD
paths:
    /api/v1/price:
        get:
            tags:
                - Price
            summary: Te saluda.
            operationId: getPrice
            parameters:
                - name: dateTime
                  in: query
                  required: true
                  schema:
                      type: string
                      format: date-time
                - name: productId
                  in: query
                  required: true
                  schema:
                      type: integer
                      format: int64
                - name: brandId
                  in: query
                  required: true
                  schema:
                      type: integer
                      format: int64
            responses:
                "200":
                    description: OK
                    content:
                        application/json:
                            schema:
                                $ref: './models/priceDTO.yaml#/components/schemas/PriceDTO'
                "400":
                    description: No content
                    content:
                        application/json:
                            schema:
                                $ref: './models/errorDTO.yaml#/components/schemas/ErrorResponseDto'
                "401":
                    description: Unauthorized
                    content:
                        application/json:
                            schema:
                                $ref: './models/errorDTO.yaml#/components/schemas/ErrorResponseDto'
                "403":
                    description: Forbidden
                    content:
                        application/json:
                            schema:
                                $ref: './models/errorDTO.yaml#/components/schemas/ErrorResponseDto'
                "404":
                    description: Not Found
                    content:
                        application/json:
                            schema:
                                $ref: './models/errorDTO.yaml#/components/schemas/ErrorResponseDto'
                "500":
                    description: Internal Server Error
                    content:
                        application/json:
                            schema:
                                $ref: './models/errorDTO.yaml#/components/schemas/ErrorResponseDto'
    /api/v1/echo:
        get:
            tags:
                - Echo
            summary: Te saluda.
            operationId: greetings
            responses:
                "200":
                    description: OK
                    content:
                        application/json:
                            schema:
                                type: string
components:
    schemas: {}
