openapi: 3.0.1
info:
    title: BCNC API
    description: API documentation for BCNC Hexagonal Prueba
    version: "1.0"
servers:
    - url: http://localhost:8080
      description: Generated server url
tags:
    - name: Price
      description: Price API for price related calls
    - name: Echo
      description: API testeo CICD
paths:
    /api/v1/price:
        get:
            tags:
                - Price
            summary: Te saluda.
            operationId: getPrice
            parameters:
                - name: dateTime
                  in: query
                  required: true
                  schema:
                      type: string
                      format: date-time
                - name: productId
                  in: query
                  required: true
                  schema:
                      type: integer
                      format: int64
                - name: brandId
                  in: query
                  required: true
                  schema:
                      type: integer
                      format: int64
            responses:
                "200":
                    description: OK
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/PriceDTO"
                "400":
                    description: No content
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/ErrorResponseDto"
                "401":
                    description: Unauthorized
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/ErrorResponseDto"
                "403":
                    description: Forbidden
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/ErrorResponseDto"
                "404":
                    description: Not Found
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/ErrorResponseDto"
                "500":
                    description: Internal Server Error
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/ErrorResponseDto"
    /api/v1/echo:
        get:
            tags:
                - Echo
            summary: Te saluda.
            operationId: greetings
            responses:
                "200":
                    description: OK
                    content:
                        application/json:
                            schema:
                                type: string
components:
    schemas:
        PriceDTO:
            type: object
            properties:
                productId:
                    type: integer
                    format: int64
                brandId:
                    type: integer
                    format: int64
                priceList:
                    type: integer
                    format: int64
                startDate:
                    type: string
                    format: date-time
                    x-field-extra-annotation: '@com.fasterxml.jackson.annotation.JsonFormat(shape = com.fasterxml.jackson.annotation.JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd HH:mm:ssXXX")'
                endDate:
                    type: string
                    format: date-time
                    x-field-extra-annotation: '@com.fasterxml.jackson.annotation.JsonFormat(shape = com.fasterxml.jackson.annotation.JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd HH:mm:ssXXX")'
                price:
                    type: string
                brandName:
                    type: string
        ErrorResponseDto:
            type: object
            properties:
                error:
                    $ref: '#/components/schemas/ErrorDto'
        ErrorDto:
            type: object
            properties:
                code:
                    type: string
                locale:
                    type: string
                description:
                    type: string
                details:
                    type: array
                    items:
                        type: string
