springdoc:
    default-produces-media-type: application/json
    packages-to-scan: com.bcnc.prueba

spring:
    h2:
        console.enabled: true
    application:
        name: prueba

    datasource:
        url: jdbc:h2:mem:prueba
        username: rootarro
        password: rootarro
        driver-class-name: org.h2.Driver
        hikari:
            idle-timeout: 10000
            minimum-idle: 2
            maximum-pool-size: 10
            max-lifetime: 30000

    jpa:
        properties:
            javax:
                persistence:
                    lock:
                        timeout: 25000
        hibernate.ddl-auto: create
        show-sql: true
        generate-ddl: false
        open-in-view: false
        database-platform: org.hibernate.dialect.H2Dialect

    flyway:
        enabled: false

server:
    port: 8080

management:
    endpoint:
        metrics:
            enabled: true
        prometheus:
            enabled: true
    metrics:
        export:
            prometheus:
                enabled: true
    endpoints:
        web:
            exposure:
                include: [ info, health, metrics, prometheus ]

