name: Java CI with Maven build

on:
    push:
        branches: [ "main" ]
    pull_request:
        branches: [ "main" ]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
            - name: Set up JDK 17
              uses: actions/setup-java@v4
              with:
                  java-version: '17'
                  distribution: 'temurin'
                  cache: maven
            - name: Verify OpenAPI file
              run: ls -R driving/api-rest/openapi/ || echo "OpenAPI file not found"
            - name: Build with Maven
              run: mvn clean install -e -X
            - name: Maven test
              run: mvn test
